<a href="https://colab.research.google.com/github/BodyNo12138/Limu/blob/main/quanzhongshuaitui.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
!pip install -U d2l

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [118]:
import torch
from torch import nn
from d2l import torch as d2l

In [119]:
num_inputs,n_train,n_test,batch_size=200,20,100,5
true_w = torch.ones((num_inputs,1)) * 0.01
true_b = 0.05

features1,labels1 = d2l.synthetic_data(true_w,true_b,n_train)
train_iter = d2l.load_array((features1,labels1),batch_size,is_train=True)
#test_data = d2l.synthetic_data(true_w,true_b,n_test)
#test_iter = d2l.load_array(test_data,batch_size,is_train=False)
features,labels = d2l.synthetic_data(true_w,true_b,n_test)

print(true_w[0],true_b,features1,labels1)

tensor([0.0100]) 0.05 tensor([[-1.3568, -0.1741, -0.7333,  ..., -0.2317, -0.0369,  0.8692],
        [-0.6509, -1.2150, -1.3857,  ..., -1.3276, -1.1004,  0.7631],
        [-0.8632,  1.5556, -0.9794,  ..., -0.6905,  0.5707, -0.9708],
        ...,
        [ 0.3165, -0.9297, -0.6688,  ..., -0.5767, -1.7588, -0.6534],
        [-0.2648,  2.1460,  0.2325,  ...,  1.7566,  0.6628, -2.5197],
        [-0.8632,  0.0942,  0.7346,  ..., -0.2723,  1.4305,  0.4355]]) tensor([[-0.0523],
        [-0.1758],
        [ 0.1844],
        [-0.0573],
        [ 0.1360],
        [-0.1547],
        [-0.3368],
        [ 0.1615],
        [ 0.1946],
        [ 0.1170],
        [ 0.0723],
        [-0.1167],
        [ 0.1507],
        [ 0.1725],
        [-0.0396],
        [ 0.0377],
        [ 0.1293],
        [ 0.2116],
        [-0.2232],
        [-0.1080]])


In [120]:
net = nn.Sequential(nn.Linear(num_inputs,1))

w = net[0].weight.data.normal_(0,1)
net[0].bias.data.fill_(0)

tensor([0.])

In [124]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(),lr=0.003)

In [125]:
def penalty(w):
  return torch.sum(w.pow(2)) / 2
print(net[0].weight,net[0].bias)

Parameter containing:
tensor([[ 1.3040, -0.8401,  1.7134,  0.7451, -0.0871,  1.0195,  0.9722, -1.7995,
         -0.7310, -0.1511, -0.0444,  0.6069,  1.2303, -0.5701, -0.0093,  0.1886,
         -0.9114, -0.0839,  0.0778,  1.1007,  0.2627,  0.7345,  0.7013,  1.1406,
         -0.2000,  0.1496,  0.7005,  1.1503, -1.6667,  0.2196,  1.3915,  0.2528,
          0.7316, -0.5491,  0.1218, -2.4390, -0.8512,  1.5726, -0.1145,  0.7088,
          0.2057,  0.5856, -0.7822,  0.1897, -0.7355,  1.5140, -0.2452, -0.8456,
         -0.0861, -0.4555,  1.0673,  0.5103, -0.0410, -1.3030, -1.5094,  0.1821,
         -0.9286, -1.5796,  0.3158,  0.2044, -1.2194,  0.4989,  0.3326, -0.1501,
          0.1194,  0.7341, -0.6465, -0.4854,  0.3876, -0.1609,  0.9198,  1.6987,
         -0.3911, -0.0827,  0.5209,  0.1266,  0.3042,  0.2822,  1.0354,  0.5782,
         -1.6598,  0.8270, -0.4691,  0.8868,  0.5437,  0.3749, -0.8133,  1.2337,
          0.0680,  0.0609, -0.4944,  0.1079, -0.1658,  0.2966,  0.9141,  0.7897,
      

In [128]:
num_epochs = 40
A,B = test_data
lambd = 3

for epoch in range(num_epochs):
  for X,y in train_iter:
   l = loss(net(X),y) + lambd * penalty(w)
   trainer.zero_grad()
   l.backward()
   trainer.step()
  l1 = loss(net(features),labels)
  l = loss(net(features1),labels1)
  print(l1,l)


tensor(165.8094, grad_fn=<MseLossBackward0>) tensor(0.0013, grad_fn=<MseLossBackward0>)
tensor(165.8120, grad_fn=<MseLossBackward0>) tensor(0.0009, grad_fn=<MseLossBackward0>)
tensor(165.8139, grad_fn=<MseLossBackward0>) tensor(0.0006, grad_fn=<MseLossBackward0>)
tensor(165.8154, grad_fn=<MseLossBackward0>) tensor(0.0004, grad_fn=<MseLossBackward0>)
tensor(165.8165, grad_fn=<MseLossBackward0>) tensor(0.0003, grad_fn=<MseLossBackward0>)
tensor(165.8177, grad_fn=<MseLossBackward0>) tensor(0.0002, grad_fn=<MseLossBackward0>)
tensor(165.8184, grad_fn=<MseLossBackward0>) tensor(0.0001, grad_fn=<MseLossBackward0>)
tensor(165.8190, grad_fn=<MseLossBackward0>) tensor(8.1029e-05, grad_fn=<MseLossBackward0>)
tensor(165.8197, grad_fn=<MseLossBackward0>) tensor(5.4731e-05, grad_fn=<MseLossBackward0>)
tensor(165.8202, grad_fn=<MseLossBackward0>) tensor(3.6870e-05, grad_fn=<MseLossBackward0>)
tensor(165.8204, grad_fn=<MseLossBackward0>) tensor(2.5008e-05, grad_fn=<MseLossBackward0>)
tensor(165.8208,